apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment10
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
      environment: production
      tier: frontend
  template:
    metadata:
      labels:
        app: nginx
        environment: production
        tier: frontend
    spec:
      containers:
      - name: nginx
        image: mohan14242/home:1.0
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-serve
spec:
  type: NodePort
  selector:
    app: nginx
    environment: production
    tier: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30000
