apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx2
      env: dev
  template:
    metadata:
      labels:
        app: nginx1
        env: dev
    spec:
      containers:
      - name: nginx
        image: mohan14242/home:1.0
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service1
spec:
  type: NodePort
  selector:
    app: nginx1
    env: dev
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

