apiVersion: v1 
kind: ConfigMap 
metadata: 
  name: filebeat-config 
data:
  filebeat.yml: | 
    fllebeat:
      config:
        modules:
          path: /usr/share/filebeat/modules.d/*.yml
          reload:
            enabled: true
      modules:
      - module: nginx
      access:
        var.paths: ["/path/to/log/nginx/access.log*"]
      error:
        var.paths: ["/path/to/log/nginx/error.log*"]
    output:
      elasticsearch:
        hosts:["elasticsearch:8080"]
--- 
apiVersion: v1 
kind: Deployment 
metadata: 
  name: nginx 
  labels: 
    env: dev 
spec: 
  replicas: 2 
  selector:
    matchLabels:
      app: nginx 
  template: 
    metadata: 
      name: nginx-container 
      labels: 
        app: nginx 
    spec: 
      containers: 
        - name: nginx-c 
          image: nginx 
          port: 
            - containerPort: 80 
            
