apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-config
data:
  filebeat.yml: |
    filebeat:
      config:
        modules:
          path: /usr/share/filebeat/modules.d/*.yml
          reload:
            enabled: true
      modules:
      - module: nginx
        access:
          enabled: true
          var.paths: ["/path/to/log/nginx/access.log*"]
        error:
          enabled: true
          var.paths: ["/path/to/log/nginx/error.log*"]
    output:
      elasticsearch:
        hosts: ["elasticsearch:8080"]

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx-c
          image: nginx
          ports:
            - containerPort: 80
      volumes: 
      - name: nginx-logs 
      - name: filebeat-configmap 
        ConfigMap: 
          name: filebeat-config
          items: 
            - key: filebeat.yml 
              path: filebeat.yml
  
