apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment10
  labels:
    name: {{.values.metadata.name}}
    env: {{.values.metadata.env}}
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
