apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .values.name }}-deployment
  labels:
    app: nginx
spec:
  replicas: {{ .values.replicas }}
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
