apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1
spec:
  replicas: 3  # Number of Nginx pods you want to run
  selector:
    matchLabels:
      app: nginx1
  template:
    metadata:
      labels:
        app: nginx1
    spec:
      containers:
      - name: nginx
        image: mohan14242/app1:v1
        ports:
        - containerPort: 80
--- 
apiVersion: v1
kind: Service
metadata:
  name: app1
spec:
  selector:
    app: nginx1 # Selects pods with label "app: nginx"
  ports:
    - protocol: TCP
      port: 80  # Exposes Nginx on port 80
      targetPort: 80  # Routes traffic to port 80 of pods
   # Exposes the service externally using a cloud provider's load balancer (Change this if needed)
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: app1
    annotations:
        alb.ingress.kubernetes.io/scheme: internet-facing
        alb.ingress.kubernetes.io/target-type: ip
        alb.ingress.kubernetes.io/tags: Environment=dev,Project=roboshop
        alb.ingress.kubernetes.io/group.name: joindevops
spec:
  ingressClassName: alb
  rules:
  - host: "app1.joindevops.online"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: app1
            port:
              number: 80